# Generated by Django 4.2.3 on 2023-09-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=7, verbose_name='Registration Number')),
                ('capacity', models.IntegerField(default=36, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='Origin')),
                ('destination', models.CharField(max_length=50, verbose_name='Destination')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
